# Generated by Django 2.2.10 on 2020-07-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/slider')),
                ('titre', models.CharField(max_length=225)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentation',
            },
        ),
        migrations.CreateModel(
            name='Reseaux_sociaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('facebook', 'fa fa-facebok'), ('twitter', 'fa fa-twitter'), ('rss', 'fa fa-rss'), ('goole-plus', 'fa fa-goole-plus'), ('linkedin', 'fa fa-linkedin'), ('pinterest', 'fa fa-pinterest')], max_length=225)),
                ('nom', models.CharField(max_length=225)),
                ('lien', models.URLField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentation',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/slider')),
                ('titre', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('map_url', models.TextField()),
                ('icon', models.ImageField(upload_to='image/SiteInfo')),
                ('logo', models.ImageField(upload_to='image/SiteInfo')),
                ('description', models.TextField()),
                ('nom', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentation',
            },
        ),
    ]
