# Generated by Django 2.2.10 on 2020-07-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200712_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='date_add',
            new_name='date',
        ),
    ]
