# Generated by Django 2.2.10 on 2020-07-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200712_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/Trending2')),
                ('titre', models.CharField(max_length=225, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending2_categories', to='website.Categories')),
            ],
            options={
                'verbose_name': 'Trending2',
                'verbose_name_plural': 'Trending2',
            },
        ),
    ]
