# Generated by Django 2.2.10 on 2020-07-11 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='email',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(null=True, upload_to='images/categories'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_commentaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='blog.Categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='image/slider'),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='message',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nom',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
