# Generated by Django 2.2.10 on 2020-07-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200711_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nombre_de_vue',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
