# Generated by Django 2.2.10 on 2020-07-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_nombre_de_vue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='image',
        ),
    ]
