# Generated by Django 2.2.10 on 2020-07-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='user',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='nom',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
